### PR TITLE
Reduce DNS cache TTL by adding resolver config to upstream entries

### PR DESCRIPTION
**Pull request by marians**
To influence DNS caches and make them short-lived

### CODE REVIEW

**Comment by ubergesundheit** [comment]
I would suggest putting 

```
resolver coredns.kube-system.svc.cluster.local valid=30s;
```

into the `server` block in [here](https://github.com/giantswarm/docs-proxy/blob/main/nginx.conf#L30)

**Comment by marians** [comment]
All right, changed

**Review by ubergesundheit — APPROVED** [review]
Just changed the deployment on gollum/c68pn to use the container image of your commit 796f064 and it still works (on my side)

**Comment by teemow** [comment]
@marians I believe this broke running the docs via docker compose. How do you run the docs locally?

**Comment by teemow** [comment]
Solved by adding this to `/etc/hosts` on my machine

```
127.0.0.11 coredns.kube-system.svc.cluster.local
```

**Comment by marians** [comment]
Good catch! I think we should revert the change.

**Comment by teemow** [comment]
Sry. I was talking about this guide and it should be in the `docs` repo: https://intranet.giantswarm.io/docs/product/docs/docs-dev/

**Pull request merged**
